services:
  portfolio:
    build: .
    container_name: portfolio
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - taurus

networks:
  taurus:
    external: true
    name: taurus
